security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Auth\Usuario
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|assets|build)/
            security: false

        # 1. Firewall para o Login
        # Alterado para cobrir especificamente o endpoint de check
        login:
            pattern: ^/api/login_check
            stateless: true
            json_login:
                check_path: /api/login_check
                provider: app_user_provider
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # 2. Firewall para a API
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            jwt: ~

    access_control:
        # Permite que o login_check seja acessado sem token
        - { path: ^/api/login_check, roles: PUBLIC_ACCESS }
        # Todo o resto da API exige autenticação
        - { path: ^/api,             roles: IS_AUTHENTICATED_FULLY }