<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520030528 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE auth.assinaturas DROP CONSTRAINT assinaturas_id_usuario_fkey');
        $this->addSql('ALTER TABLE avaliacao.avaliacoes DROP CONSTRAINT avaliacoes_id_servico_fkey');
        $this->addSql('ALTER TABLE avaliacao.imagens DROP CONSTRAINT imagens_id_avaliacao_fkey');
        $this->addSql('ALTER TABLE empresarial.empresa_prestadores DROP CONSTRAINT empresa_prestadores_id_empresa_fkey');
        $this->addSql('ALTER TABLE empresarial.empresas DROP CONSTRAINT empresas_id_fkey');
        $this->addSql('DROP TABLE auth.assinaturas');
        $this->addSql('DROP TABLE avaliacao.avaliacoes');
        $this->addSql('DROP TABLE avaliacao.imagens');
        $this->addSql('DROP TABLE empresarial.empresa_prestadores');
        $this->addSql('DROP TABLE empresarial.empresas');
        $this->addSql('ALTER TABLE servico.agendamentos ADD status INT NOT NULL');
        $this->addSql('ALTER TABLE servico.agendamentos DROP id_status');
        $this->addSql('ALTER TABLE servico.agendamentos ALTER criado_em DROP DEFAULT');
        $this->addSql('ALTER TABLE localizacao.cep ALTER numero TYPE VARCHAR(9)');
        $this->addSql('ALTER TABLE servico.clientes ALTER criado_em DROP DEFAULT');
        $this->addSql('ALTER TABLE localizacao.enderecos ALTER cep TYPE VARCHAR(9)');
        $this->addSql('DROP INDEX portifolio.fotos_id_projeto_posicao_key');
        $this->addSql('ALTER TABLE portifolio.fotos RENAME COLUMN posicao TO ordem');
        $this->addSql('CREATE UNIQUE INDEX uniq_projeto_ordem ON portifolio.fotos (id_projeto, ordem)');
        $this->addSql('ALTER INDEX portifolio.idx__fotos__id_projeto RENAME TO IDX_415C29677EC834E4');
        $this->addSql('ALTER TABLE chat.mensagens ALTER envio_em DROP DEFAULT');
        $this->addSql('ALTER TABLE chat.mensagens ALTER envio_em SET NOT NULL');
        $this->addSql('ALTER INDEX chat.idx__mensagens__id_sala RENAME TO IDX_C4BA96AB6906181E');
        $this->addSql('ALTER TABLE localizacao.municipios ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE localizacao.municipios ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE localizacao.municipios ALTER codigo_ibge TYPE VARCHAR(7)');
        $this->addSql('ALTER TABLE localizacao.municipios ALTER uf TYPE VARCHAR(2)');
        $this->addSql('ALTER INDEX localizacao.municipios_codigo_ibge_key RENAME TO UNIQ_D01123965B9F2D9E');
        $this->addSql('ALTER TABLE servico.orcamentos ALTER criado_em DROP DEFAULT');
        $this->addSql('ALTER TABLE auth.perfis DROP CONSTRAINT perfis_id_fkey');
        $this->addSql('ALTER TABLE auth.perfis ADD CONSTRAINT FK_71D107CFBF396750 FOREIGN KEY (id) REFERENCES auth.usuarios (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE portifolio.portifolios DROP CONSTRAINT portifolios_id_fkey');
        $this->addSql('ALTER TABLE portifolio.portifolios ALTER servicos_concluidos DROP DEFAULT');
        $this->addSql('ALTER TABLE servico.prestadores ADD cidade VARCHAR(100) NOT NULL');
        $this->addSql('ALTER TABLE servico.prestadores DROP cep');
        $this->addSql('ALTER TABLE servico.prestadores ALTER ativo DROP DEFAULT');
        $this->addSql('ALTER TABLE servico.prestadores ALTER criado_em DROP DEFAULT');
        $this->addSql('ALTER TABLE servico.prestadores_profissoes DROP CONSTRAINT prestadores_profissoes_id_prestador_fkey');
        $this->addSql('ALTER TABLE servico.prestadores_profissoes DROP CONSTRAINT prestadores_profissoes_id_profissao_fkey');
        $this->addSql('ALTER TABLE servico.prestadores_profissoes DROP qtd_prestacoes');
        $this->addSql('ALTER TABLE servico.prestadores_profissoes DROP med_avaliacoes');
        $this->addSql('ALTER TABLE servico.prestadores_profissoes DROP criado_em');
        $this->addSql('ALTER TABLE servico.prestadores_profissoes DROP excluido_em');
        $this->addSql('ALTER TABLE servico.prestadores_profissoes ADD CONSTRAINT FK_D32BDF7AB0AA3371 FOREIGN KEY (id_prestador) REFERENCES servico.prestadores (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE servico.prestadores_profissoes ADD CONSTRAINT FK_D32BDF7AC14DC792 FOREIGN KEY (id_profissao) REFERENCES servico.profissoes (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE servico.profissoes ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE servico.profissoes ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE servico.profissoes ALTER criado_em DROP DEFAULT');
        $this->addSql('ALTER TABLE servico.profissoes ALTER criado_em SET NOT NULL');
        $this->addSql('ALTER INDEX servico.profissoes_descricao_key RENAME TO UNIQ_13FF691522B85EB');
        $this->addSql('ALTER TABLE portifolio.projetos DROP CONSTRAINT projetos_id_servico_fkey');
        $this->addSql('DROP INDEX portifolio.projetos_id_portifolio_posicao_key');
        $this->addSql('DROP INDEX portifolio.IDX_848DA169DFD5DABC');
        $this->addSql('ALTER TABLE portifolio.projetos DROP id_servico');
        $this->addSql('ALTER TABLE portifolio.projetos DROP posicao');
        $this->addSql('ALTER TABLE portifolio.projetos ALTER exibir_valor DROP DEFAULT');
        $this->addSql('ALTER TABLE portifolio.projetos ALTER exibir_concluido_em DROP DEFAULT');
        $this->addSql('ALTER TABLE chat.sala ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE chat.sala ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX chat.sala_id_servico_key RENAME TO UNIQ_80085022DFD5DABC');
        $this->addSql('ALTER TABLE servico.servicos DROP CONSTRAINT servicos_id_cliente_fkey');
        $this->addSql('ALTER TABLE servico.servicos DROP CONSTRAINT servicos_id_prestador_fkey');
        $this->addSql('ALTER TABLE servico.servicos ALTER id_status DROP DEFAULT');
        $this->addSql('ALTER TABLE servico.servicos ALTER inicio DROP DEFAULT');
        $this->addSql('ALTER TABLE servico.servicos ADD CONSTRAINT FK_805115812A813255 FOREIGN KEY (id_cliente) REFERENCES auth.usuarios (id)');
        $this->addSql('ALTER TABLE servico.servicos ADD CONSTRAINT FK_80511581B0AA3371 FOREIGN KEY (id_prestador) REFERENCES auth.usuarios (id)');
        $this->addSql('ALTER TABLE auth.usuarios ALTER roles TYPE JSON');
        $this->addSql('ALTER INDEX auth.usuarios_email_key RENAME TO UNIQ_CDD4D7E2E7927C74');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA empresarial');
        $this->addSql('CREATE SCHEMA avaliacao');
        $this->addSql('CREATE TABLE auth.assinaturas (id_usuario UUID NOT NULL, tipo VARCHAR(20) NOT NULL, ativo BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id_usuario, tipo))');
        $this->addSql('CREATE INDEX IDX_38D906B4FCF8192D ON auth.assinaturas (id_usuario)');
        $this->addSql('CREATE TABLE avaliacao.avaliacoes (id_servico UUID NOT NULL, nota DOUBLE PRECISION NOT NULL, comentario TEXT DEFAULT NULL, PRIMARY KEY (id_servico))');
        $this->addSql('CREATE TABLE avaliacao.imagens (id UUID NOT NULL, id_avaliacao UUID NOT NULL, caminho VARCHAR(512) NOT NULL, mime_type VARCHAR(100) NOT NULL, tamanho INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx__imagens__id_avaliacao ON avaliacao.imagens (id_avaliacao)');
        $this->addSql('CREATE TABLE empresarial.empresa_prestadores (id_empresa UUID NOT NULL, id_prestador UUID NOT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, excluido_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id_prestador))');
        $this->addSql('CREATE INDEX IDX_1C76FEF7664AF320 ON empresarial.empresa_prestadores (id_empresa)');
        $this->addSql('CREATE TABLE empresarial.empresas (id UUID NOT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, excluido_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE auth.assinaturas ADD CONSTRAINT assinaturas_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES auth.usuarios (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE avaliacao.avaliacoes ADD CONSTRAINT avaliacoes_id_servico_fkey FOREIGN KEY (id_servico) REFERENCES servico.servicos (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE avaliacao.imagens ADD CONSTRAINT imagens_id_avaliacao_fkey FOREIGN KEY (id_avaliacao) REFERENCES avaliacao.avaliacoes (id_servico) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE empresarial.empresa_prestadores ADD CONSTRAINT empresa_prestadores_id_empresa_fkey FOREIGN KEY (id_empresa) REFERENCES empresarial.empresas (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE empresarial.empresas ADD CONSTRAINT empresas_id_fkey FOREIGN KEY (id) REFERENCES auth.usuarios (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE auth.perfis DROP CONSTRAINT FK_71D107CFBF396750');
        $this->addSql('ALTER TABLE auth.perfis ADD CONSTRAINT perfis_id_fkey FOREIGN KEY (id) REFERENCES auth.usuarios (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE auth.usuarios ALTER roles TYPE JSONB');
        $this->addSql('ALTER INDEX auth.uniq_cdd4d7e2e7927c74 RENAME TO usuarios_email_key');
        $this->addSql('ALTER TABLE chat.mensagens ALTER envio_em SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE chat.mensagens ALTER envio_em DROP NOT NULL');
        $this->addSql('ALTER INDEX chat.idx_c4ba96ab6906181e RENAME TO idx__mensagens__id_sala');
        $this->addSql('ALTER TABLE chat.sala ALTER id SET DEFAULT nextval(\'chat.sala_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE chat.sala ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX chat.uniq_80085022dfd5dabc RENAME TO sala_id_servico_key');
        $this->addSql('ALTER TABLE localizacao.cep ALTER numero TYPE CHAR(9)');
        $this->addSql('ALTER TABLE localizacao.enderecos ALTER cep TYPE CHAR(9)');
        $this->addSql('ALTER TABLE localizacao.municipios ALTER codigo_ibge TYPE CHAR(7)');
        $this->addSql('ALTER TABLE localizacao.municipios ALTER uf TYPE CHAR(2)');
        $this->addSql('ALTER TABLE localizacao.municipios ALTER id SET DEFAULT nextval(\'localizacao.municipios_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE localizacao.municipios ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX localizacao.uniq_d01123965b9f2d9e RENAME TO municipios_codigo_ibge_key');
        $this->addSql('DROP INDEX portifolio.uniq_projeto_ordem');
        $this->addSql('ALTER TABLE portifolio.fotos RENAME COLUMN ordem TO posicao');
        $this->addSql('CREATE UNIQUE INDEX fotos_id_projeto_posicao_key ON portifolio.fotos (id_projeto, posicao)');
        $this->addSql('ALTER INDEX portifolio.idx_415c29677ec834e4 RENAME TO idx__fotos__id_projeto');
        $this->addSql('ALTER TABLE portifolio.portifolios ALTER servicos_concluidos SET DEFAULT 0');
        $this->addSql('ALTER TABLE portifolio.portifolios ADD CONSTRAINT portifolios_id_fkey FOREIGN KEY (id) REFERENCES servico.prestadores (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE portifolio.projetos ADD id_servico UUID NOT NULL');
        $this->addSql('ALTER TABLE portifolio.projetos ADD posicao INT NOT NULL');
        $this->addSql('ALTER TABLE portifolio.projetos ALTER exibir_valor SET DEFAULT true');
        $this->addSql('ALTER TABLE portifolio.projetos ALTER exibir_concluido_em SET DEFAULT true');
        $this->addSql('ALTER TABLE portifolio.projetos ADD CONSTRAINT projetos_id_servico_fkey FOREIGN KEY (id_servico) REFERENCES servico.servicos (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX projetos_id_portifolio_posicao_key ON portifolio.projetos (id_portifolio, posicao)');
        $this->addSql('CREATE INDEX IDX_848DA169DFD5DABC ON portifolio.projetos (id_servico)');
        $this->addSql('ALTER TABLE servico.agendamentos ADD id_status INT DEFAULT 1 NOT NULL');
        $this->addSql('ALTER TABLE servico.agendamentos DROP status');
        $this->addSql('ALTER TABLE servico.agendamentos ALTER criado_em SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE servico.clientes ALTER criado_em SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE servico.orcamentos ALTER criado_em SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE servico.prestadores ADD cep CHAR(8) NOT NULL');
        $this->addSql('ALTER TABLE servico.prestadores DROP cidade');
        $this->addSql('ALTER TABLE servico.prestadores ALTER ativo SET DEFAULT true');
        $this->addSql('ALTER TABLE servico.prestadores ALTER criado_em SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE servico.prestadores_profissoes DROP CONSTRAINT FK_D32BDF7AB0AA3371');
        $this->addSql('ALTER TABLE servico.prestadores_profissoes DROP CONSTRAINT FK_D32BDF7AC14DC792');
        $this->addSql('ALTER TABLE servico.prestadores_profissoes ADD qtd_prestacoes INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE servico.prestadores_profissoes ADD med_avaliacoes DOUBLE PRECISION DEFAULT \'5.0\' NOT NULL');
        $this->addSql('ALTER TABLE servico.prestadores_profissoes ADD criado_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE servico.prestadores_profissoes ADD excluido_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE servico.prestadores_profissoes ADD CONSTRAINT prestadores_profissoes_id_prestador_fkey FOREIGN KEY (id_prestador) REFERENCES servico.prestadores (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE servico.prestadores_profissoes ADD CONSTRAINT prestadores_profissoes_id_profissao_fkey FOREIGN KEY (id_profissao) REFERENCES servico.profissoes (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE servico.profissoes ALTER criado_em SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE servico.profissoes ALTER criado_em DROP NOT NULL');
        $this->addSql('ALTER TABLE servico.profissoes ALTER id SET DEFAULT nextval(\'servico.profissoes_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE servico.profissoes ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX servico.uniq_13ff691522b85eb RENAME TO profissoes_descricao_key');
        $this->addSql('ALTER TABLE servico.servicos DROP CONSTRAINT FK_805115812A813255');
        $this->addSql('ALTER TABLE servico.servicos DROP CONSTRAINT FK_80511581B0AA3371');
        $this->addSql('ALTER TABLE servico.servicos ALTER id_status SET DEFAULT 1');
        $this->addSql('ALTER TABLE servico.servicos ALTER inicio SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE servico.servicos ADD CONSTRAINT servicos_id_cliente_fkey FOREIGN KEY (id_cliente) REFERENCES servico.clientes (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE servico.servicos ADD CONSTRAINT servicos_id_prestador_fkey FOREIGN KEY (id_prestador) REFERENCES servico.prestadores (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
